remote_theme: pages-themes/cayman@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Diversity Impact in Movie Success
description: "DRACO team: Abdul Ameer Ali, Bejan Diana, Peseux Romain, Samanos Clément, Voland Océane" 
show_downloads: True
